using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Collections.Generic;

namespace Rymote.Radiant.Generator;

[Generator]
public class ModelSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all class declarations
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => ctx.Node as ClassDeclarationSyntax
            )
            .Where(static c => c is not null);

        // Combine with compilation
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
        {
            var (compilation, classes) = source;
            
            foreach (var classDeclaration in classes)
            {
                if (classDeclaration == null) continue;
                
                // Get semantic model
                var model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
                var symbol = model.GetDeclaredSymbol(classDeclaration);
                
                if (symbol is not INamedTypeSymbol classSymbol)
                    continue;

                // Check if class has [Table] attribute
                var hasTableAttribute = classSymbol.GetAttributes()
                    .Any(a => a.AttributeClass?.Name == "TableAttribute" || 
                             a.AttributeClass?.ToDisplayString() == "Rymote.Radiant.Core.Attributes.TableAttribute");
                
                if (!hasTableAttribute)
                    continue;

                // Generate code for this class
                var generator = new ModelSourceGenerator();
                var generatedCode = generator.GenerateModelExtensions(classSymbol);
                spc.AddSource($"{classSymbol.Name}Extensions.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
            }
        });
    }

    private string GenerateModelExtensions(INamedTypeSymbol classSymbol)
    {
        string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        string className = classSymbol.Name;

        string tableName = GetTableName(classSymbol);
        string schemaName = GetSchemaName(classSymbol);

        List<PropertyInfo> properties = GetColumnProperties(classSymbol);

        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Dapper;");
        sb.AppendLine("using Rymote.Radiant.Core.Attributes;");
        sb.AppendLine("using Rymote.Radiant.Models;");
        sb.AppendLine("using Rymote.Radiant.Query;");
        sb.AppendLine();
        
        // Handle global namespace
        bool hasNamespace = !string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>";
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
        }
        
        sb.AppendLine($"{(hasNamespace ? "    " : "")}public static class {className}Extensions");
        sb.AppendLine($"{(hasNamespace ? "    " : "")}{{");

        // Generate column constants
        string indent = hasNamespace ? "        " : "    ";
        sb.AppendLine($"{indent}public static class Columns");
        sb.AppendLine($"{indent}{{");
        foreach (PropertyInfo prop in properties)
        {
            sb.AppendLine($"{indent}    public const string {prop.PropertyName} = \"{prop.ColumnName}\";");
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        // Generate typed query methods
        foreach (PropertyInfo prop in properties)
        {
            string methodName = $"Where{prop.PropertyName}";
            string paramType = prop.PropertyType;

            // Equals
            sb.AppendLine($"{indent}public static QueryBuilder<{className}> {methodName}(this QueryBuilder<{className}> query, {paramType} value)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    return query.Where(Columns.{prop.PropertyName}, \"=\", value);");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();

            // In
            sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}In(this QueryBuilder<{className}> query, IEnumerable<{paramType}> values)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return query.WhereIn(Columns.{prop.PropertyName}, values);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // NotIn
            sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}NotIn(this QueryBuilder<{className}> query, IEnumerable<{paramType}> values)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return query.WhereNotIn(Columns.{prop.PropertyName}, values);");
            sb.AppendLine("        }");
            sb.AppendLine();

            if (paramType == "string" || paramType == "string?")
            {
                // Like
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}Like(this QueryBuilder<{className}> query, string pattern)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.WhereLike(Columns.{prop.PropertyName}, pattern);");
                sb.AppendLine("        }");
                sb.AppendLine();

                // StartsWith
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}StartsWith(this QueryBuilder<{className}> query, string prefix)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.WhereLike(Columns.{prop.PropertyName}, prefix + \"%\");");
                sb.AppendLine("        }");
                sb.AppendLine();

                // EndsWith
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}EndsWith(this QueryBuilder<{className}> query, string suffix)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.WhereLike(Columns.{prop.PropertyName}, \"%\" + suffix);");
                sb.AppendLine("        }");
                sb.AppendLine();

                // Contains
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}Contains(this QueryBuilder<{className}> query, string substring)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.WhereLike(Columns.{prop.PropertyName}, \"%\" + substring + \"%\");");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            if (IsComparableType(paramType))
            {
                // GreaterThan
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}GreaterThan(this QueryBuilder<{className}> query, {paramType} value)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.Where(Columns.{prop.PropertyName}, \">\", value);");
                sb.AppendLine("        }");
                sb.AppendLine();

                // GreaterThanOrEqual
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}GreaterThanOrEqual(this QueryBuilder<{className}> query, {paramType} value)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.Where(Columns.{prop.PropertyName}, \">=\", value);");
                sb.AppendLine("        }");
                sb.AppendLine();

                // LessThan
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}LessThan(this QueryBuilder<{className}> query, {paramType} value)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.Where(Columns.{prop.PropertyName}, \"<\", value);");
                sb.AppendLine("        }");
                sb.AppendLine();

                // LessThanOrEqual
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}LessThanOrEqual(this QueryBuilder<{className}> query, {paramType} value)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.Where(Columns.{prop.PropertyName}, \"<=\", value);");
                sb.AppendLine("        }");
                sb.AppendLine();

                // Between
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}Between(this QueryBuilder<{className}> query, {paramType} start, {paramType} end)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.WhereBetween(Columns.{prop.PropertyName}, start, end);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            if (IsDateTimeType(paramType))
            {
                // Date
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}Date(this QueryBuilder<{className}> query, DateTime date)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.WhereDate(Columns.{prop.PropertyName}, date);");
                sb.AppendLine("        }");
                sb.AppendLine();

                // Year
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}Year(this QueryBuilder<{className}> query, int year)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.WhereYear(Columns.{prop.PropertyName}, year);");
                sb.AppendLine("        }");
                sb.AppendLine();

                // Month
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}Month(this QueryBuilder<{className}> query, int month)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.WhereMonth(Columns.{prop.PropertyName}, month);");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            if (prop.IsNullable)
            {
                // IsNull
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}IsNull(this QueryBuilder<{className}> query)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.WhereNull(Columns.{prop.PropertyName});");
                sb.AppendLine("        }");
                sb.AppendLine();

                // IsNotNull
                sb.AppendLine($"        public static QueryBuilder<{className}> {methodName}IsNotNull(this QueryBuilder<{className}> query)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return query.WhereNotNull(Columns.{prop.PropertyName});");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            // OrderBy
            sb.AppendLine($"        public static QueryBuilder<{className}> OrderBy{prop.PropertyName}(this QueryBuilder<{className}> query)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return query.OrderBy(Columns.{prop.PropertyName});");
            sb.AppendLine("        }");
            sb.AppendLine();

            // OrderByDesc
            sb.AppendLine($"        public static QueryBuilder<{className}> OrderBy{prop.PropertyName}Desc(this QueryBuilder<{className}> query)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return query.OrderByDesc(Columns.{prop.PropertyName});");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // Generate mapping methods
        var columnList = string.Join(", ", properties.Select(p => p.ColumnName));
        var insertableProperties = properties.Where(p => !p.IsAutoGenerated).ToList();
        var insertColumnList = string.Join(", ", insertableProperties.Select(p => p.ColumnName));
        var insertParamList = string.Join(", ", insertableProperties.Select(p => $"@{p.PropertyName}"));
        var paramList = string.Join(", ", properties.Select(p => $"@{p.PropertyName}"));
        var updateList = string.Join(", ", properties.Where(p => !p.IsAutoGenerated).Select(p => $"{p.ColumnName} = @{p.PropertyName}"));
        var primaryKey = properties.FirstOrDefault(p => p.IsPrimaryKey);

        if (primaryKey != null)
        {
            // Find
            sb.AppendLine($"        public static async Task<{className}?> FindAsync(this IDbConnection connection, {primaryKey.PropertyType} id)");
            sb.AppendLine("        {");
            sb.AppendLine($"            const string sql = \"SELECT {columnList} FROM {tableName} WHERE {primaryKey.ColumnName} = @Id\";");
            sb.AppendLine("            var parameters = new DynamicParameters();");
            sb.AppendLine("            parameters.Add(\"@Id\", id);");
            sb.AppendLine($"            return await connection.QuerySingleOrDefaultAsync<{className}>(sql, parameters);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Update
            sb.AppendLine($"        public static async Task<int> UpdateAsync(this IDbConnection connection, {className} model)");
            sb.AppendLine("        {");
            sb.AppendLine($"            const string sql = \"UPDATE {tableName} SET {updateList} WHERE {primaryKey.ColumnName} = @{primaryKey.PropertyName}\";");
            sb.AppendLine("            return await connection.ExecuteAsync(sql, model);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Delete
            sb.AppendLine($"        public static async Task<int> DeleteAsync(this IDbConnection connection, {primaryKey.PropertyType} id)");
            sb.AppendLine("        {");
            sb.AppendLine($"            const string sql = \"DELETE FROM {tableName} WHERE {primaryKey.ColumnName} = @Id\";");
            sb.AppendLine("            var parameters = new DynamicParameters();");
            sb.AppendLine("            parameters.Add(\"@Id\", id);");
            sb.AppendLine("            return await connection.ExecuteAsync(sql, parameters);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // BulkInsert
            sb.AppendLine($"        public static async Task<int> BulkInsertAsync(this IDbConnection connection, IEnumerable<{className}> models)");
            sb.AppendLine("        {");
            sb.AppendLine($"            const string sql = \"INSERT INTO {tableName} ({insertColumnList}) VALUES ({insertParamList})\";");
            sb.AppendLine("            return await connection.ExecuteAsync(sql, models);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // BulkUpdate
            sb.AppendLine($"        public static async Task<int> BulkUpdateAsync(this IDbConnection connection, IEnumerable<{className}> models)");
            sb.AppendLine("        {");
            sb.AppendLine($"            const string sql = \"UPDATE {tableName} SET {updateList} WHERE {primaryKey.ColumnName} = @{primaryKey.PropertyName}\";");
            sb.AppendLine("            return await connection.ExecuteAsync(sql, models);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // BulkDelete
            sb.AppendLine($"        public static async Task<int> BulkDeleteAsync(this IDbConnection connection, IEnumerable<{primaryKey.PropertyType}> ids)");
            sb.AppendLine("        {");
            sb.AppendLine($"            const string sql = \"DELETE FROM {tableName} WHERE {primaryKey.ColumnName} = ANY(@Ids)\";");
            sb.AppendLine("            var parameters = new DynamicParameters();");
            sb.AppendLine("            parameters.Add(\"@Ids\", ids);");
            sb.AppendLine("            return await connection.ExecuteAsync(sql, parameters);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        
        // Close namespace if we opened one
        if (!string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>")
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private bool IsComparableType(string typeName)
    {
        return typeName switch
        {
            "int" or "int?" or "long" or "long?" or "decimal" or "decimal?" or
                "double" or "double?" or "float" or "float?" or "DateTime" or "DateTime?" or
                "DateTimeOffset" or "DateTimeOffset?" => true,
            _ => false
        };
    }

    private bool IsDateTimeType(string typeName)
    {
        return typeName switch
        {
            "DateTime" or "DateTime?" or "DateTimeOffset" or "DateTimeOffset?" => true,
            _ => false
        };
    }

    private string GetTableName(INamedTypeSymbol classSymbol)
    {
        AttributeData? tableAttr = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "TableAttribute" || a.AttributeClass?.ToDisplayString() == "Rymote.Radiant.Core.Attributes.TableAttribute");

        if (tableAttr?.ConstructorArguments.Length > 0)
        {
            return tableAttr.ConstructorArguments[0].Value?.ToString() ?? classSymbol.Name.ToLowerInvariant();
        }

        return classSymbol.Name.ToLowerInvariant();
    }

    private string GetSchemaName(INamedTypeSymbol classSymbol)
    {
        AttributeData? tableAttr = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "TableAttribute" || a.AttributeClass?.ToDisplayString() == "Rymote.Radiant.Core.Attributes.TableAttribute");

        if (tableAttr?.NamedArguments.Any() == true)
        {
            KeyValuePair<string, TypedConstant> schemaArg = tableAttr.NamedArguments
                .FirstOrDefault(kvp => kvp.Key == "Schema");

            if (!schemaArg.Equals(default(KeyValuePair<string, TypedConstant>)))
            {
                return schemaArg.Value.Value?.ToString() ?? "public";
            }
        }

        return "public";
    }

    private List<PropertyInfo> GetColumnProperties(INamedTypeSymbol classSymbol)
    {
        List<PropertyInfo> properties = new();
        
        // Check if this class inherits from Model<T>
        var baseType = classSymbol.BaseType;
        bool inheritsFromModel = false;
        while (baseType != null)
        {
            if (baseType.Name == "Model" && baseType.TypeArguments.Length == 1)
            {
                inheritsFromModel = true;
                break;
            }
            baseType = baseType.BaseType;
        }
        
        // If it inherits from Model<T>, add the Id property
        if (inheritsFromModel)
        {
            properties.Add(new PropertyInfo
            {
                PropertyName = "Id",
                ColumnName = "id",
                PropertyType = "long",
                IsPrimaryKey = true,
                IsAutoGenerated = true,
                IsNullable = false,
                IsJsonColumn = false
            });
        }

        foreach (IPropertySymbol property in classSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (property.IsStatic || property.IsIndexer)
                continue;

            bool isPrimaryKey = property.GetAttributes()
                .Any(a => a.AttributeClass?.Name == "PrimaryKeyAttribute" || a.AttributeClass?.ToDisplayString() == "Rymote.Radiant.Core.Attributes.PrimaryKeyAttribute");

            bool isAutoGenerated = false;
            if (isPrimaryKey)
            {
                AttributeData? pkAttr = property.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "PrimaryKeyAttribute" || a.AttributeClass?.ToDisplayString() == "Rymote.Radiant.Core.Attributes.PrimaryKeyAttribute");

                if (pkAttr?.NamedArguments.Any() == true)
                {
                    KeyValuePair<string, TypedConstant> autoGenArg = pkAttr.NamedArguments
                        .FirstOrDefault(kvp => kvp.Key == "AutoGenerated");

                    if (!autoGenArg.Equals(default(KeyValuePair<string, TypedConstant>)))
                    {
                        isAutoGenerated = (bool)(autoGenArg.Value.Value ?? true);
                    }
                }
                else
                {
                    isAutoGenerated = true;
                }
            }

            AttributeData? columnAttr = property.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "ColumnAttribute" || a.AttributeClass?.ToDisplayString() == "Rymote.Radiant.Core.Attributes.ColumnAttribute");

            string columnName = property.Name.ToLowerInvariant();
            if (columnAttr?.ConstructorArguments.Length > 0)
            {
                columnName = columnAttr.ConstructorArguments[0].Value?.ToString() ?? columnName;
            }

            bool isJsonColumn = property.GetAttributes()
                .Any(a => a.AttributeClass?.Name == "JsonColumnAttribute" || a.AttributeClass?.ToDisplayString() == "Rymote.Radiant.Core.Attributes.JsonColumnAttribute");

            properties.Add(new PropertyInfo
            {
                PropertyName = property.Name,
                ColumnName = columnName,
                PropertyType = property.Type.ToDisplayString(),
                IsPrimaryKey = isPrimaryKey,
                IsAutoGenerated = isAutoGenerated,
                IsNullable = property.Type.CanBeReferencedByName && property.Type.IsReferenceType ||
                             property.Type.ToDisplayString().EndsWith("?"),
                IsJsonColumn = isJsonColumn
            });
        }

        return properties;
    }

    private class PropertyInfo
    {
        public string PropertyName { get; set; } = "";
        public string ColumnName { get; set; } = "";
        public string PropertyType { get; set; } = "";
        public bool IsPrimaryKey { get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool IsNullable { get; set; }
        public bool IsJsonColumn { get; set; }
    }
}