using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Rymote.Radiant.Generator;

[Generator]
public class QuerySourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            string optimizedQueries = GenerateOptimizedQueries();
            ctx.AddSource("OptimizedQueries.g.cs", SourceText.From(optimizedQueries, Encoding.UTF8));

            string sqlConstants = GenerateSqlConstants();
            ctx.AddSource("SqlConstants.g.cs", SourceText.From(sqlConstants, Encoding.UTF8));
        });
    }

    private string GenerateOptimizedQueries()
    {
        return """
               // <auto-generated />
               using System.Data;
               using Dapper;
               using Rymote.Radiant.Query;

               namespace Rymote.Radiant.Generated;

               public static class OptimizedQueries
               {
                   public static async Task<T?> FindByIdOptimizedAsync<T>(IDbConnection connection, string schema, string table, object id) where T : class
                   {
                       string sql = $"SELECT * FROM \"{schema}\".\"{table}\" WHERE id = @id LIMIT 1";
                       return await connection.QueryFirstOrDefaultAsync<T>(sql, new { id });
                   }
               
                   public static async Task<IEnumerable<T>> FindByIdsOptimizedAsync<T>(IDbConnection connection, string schema, string table, IEnumerable<object> ids) where T : class
                   {
                       if (!ids.Any()) return Enumerable.Empty<T>();
                       
                       string sql = $"SELECT * FROM \"{schema}\".\"{table}\" WHERE id = ANY(@ids)";
                       return await connection.QueryAsync<T>(sql, new { ids = ids.ToArray() });
                   }
               
                   public static async Task<int> CountOptimizedAsync(IDbConnection connection, string schema, string table)
                   {
                       string sql = $"SELECT COUNT(*) FROM \"{schema}\".\"{table}\"";
                       return await connection.ExecuteScalarAsync<int>(sql);
                   }
               
                   public static async Task<int> CountWithConditionOptimizedAsync(IDbConnection connection, string schema, string table, string whereClause, object parameters)
                   {
                       string sql = $"SELECT COUNT(*) FROM \"{schema}\".\"{table}\" WHERE {whereClause}";
                       return await connection.ExecuteScalarAsync<int>(sql, parameters);
                   }
               
                   public static async Task<bool> ExistsOptimizedAsync(IDbConnection connection, string schema, string table, object id)
                   {
                       string sql = $"SELECT EXISTS(SELECT 1 FROM \"{schema}\".\"{table}\" WHERE id = @id)";
                       return await connection.ExecuteScalarAsync<bool>(sql, new { id });
                   }
               }
               """;
    }

    private string GenerateSqlConstants()
    {
        return """
               // <auto-generated />
               namespace Rymote.Radiant.Generated;

               public static class SqlConstants
               {
                   public const string SelectAll = "SELECT * FROM \"{0}\".\"{1}\"";
                   public const string SelectById = "SELECT * FROM \"{0}\".\"{1}\" WHERE id = @id";
                   public const string SelectByIds = "SELECT * FROM \"{0}\".\"{1}\" WHERE id = ANY(@ids)";
                   public const string Count = "SELECT COUNT(*) FROM \"{0}\".\"{1}\"";
                   public const string CountWithWhere = "SELECT COUNT(*) FROM \"{0}\".\"{1}\" WHERE {2}";
                   public const string Exists = "SELECT EXISTS(SELECT 1 FROM \"{0}\".\"{1}\" WHERE id = @id)";
                   public const string DeleteById = "DELETE FROM \"{0}\".\"{1}\" WHERE id = @id";
                   public const string DeleteByIds = "DELETE FROM \"{0}\".\"{1}\" WHERE id = ANY(@ids)";
                   
                   public const string FastCount = "SELECT reltuples::BIGINT FROM pg_class WHERE relname = '{0}'";
                   public const string TableExists = "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = '{0}' AND table_name = '{1}')";
                   public const string ColumnExists = "SELECT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = '{0}' AND table_name = '{1}' AND column_name = '{2}')";
                   
                   public const string BulkInsertTemplate = "INSERT INTO \"{0}\".\"{1}\" ({2}) VALUES {3}";
                   public const string BulkUpdateTemplate = "UPDATE \"{0}\".\"{1}\" SET {2} WHERE id = @id";
                   
                   public const string JsonContains = "{0} @> @value::jsonb";
                   public const string JsonExtract = "{0}->'{1}'";
                   public const string JsonExtractText = "{0}->>'{1}'";
                   
                   public const string ArrayContains = "@value = ANY({0})";
                   public const string ArrayOverlap = "{0} && @values";
                   
                   public const string FullTextSearch = "to_tsvector('{0}', {1}) @@ plainto_tsquery('{0}', @query)";
                   
                   public const string WithinDistance = "ST_DWithin(ST_Point({0}, {1})::geography, ST_Point(@lon, @lat)::geography, @radius)";
                   public const string Distance = "ST_Distance(ST_Point({0}, {1})::geography, ST_Point(@lon, @lat)::geography)";
               }
               """;
    }
}