using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Rymote.Radiant.Generators;

[Generator]
public sealed class SmartModelGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> smartModelSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (syntaxNode, _) => IsCandidateClass(syntaxNode),
                transform: static (syntaxContext, cancellationToken) => GetSmartModelSymbol(syntaxContext, cancellationToken))
            .Where(static symbol => symbol is not null)
            .Select(static (symbol, _) => symbol!);

        context.RegisterSourceOutput(smartModelSymbols, static (sourceProductionContext, classSymbol) =>
        {
            string helpersCode = GenerateHelperMethods(classSymbol);
            sourceProductionContext.AddSource(
                $"{classSymbol.Name}.SmartHelpers.g.cs",
                SourceText.From(helpersCode, Encoding.UTF8));

            string mapperCode = GenerateResultMapper(classSymbol);
            sourceProductionContext.AddSource(
                $"{classSymbol.Name}.RadiantMapper.g.cs",
                SourceText.From(mapperCode, Encoding.UTF8));
        });
    }

    private static bool IsCandidateClass(SyntaxNode syntaxNode)
    {
        return syntaxNode is ClassDeclarationSyntax classDeclaration && classDeclaration.BaseList != null;
    }

    private static INamedTypeSymbol? GetSmartModelSymbol(GeneratorSyntaxContext syntaxContext, CancellationToken cancellationToken)
    {
        ClassDeclarationSyntax classDeclaration = (ClassDeclarationSyntax)syntaxContext.Node;
        INamedTypeSymbol? classSymbol = syntaxContext.SemanticModel.GetDeclaredSymbol(classDeclaration, cancellationToken) as INamedTypeSymbol;

        if (classSymbol == null) return null;
        if (classSymbol.IsAbstract) return null;
        if (classSymbol.IsGenericType && classSymbol.TypeArguments.Any(typeArgument => typeArgument is ITypeParameterSymbol)) return null;
        if (classSymbol.Name == "SmartModel") return null;

        return InheritsFromSmartModel(classSymbol) ? classSymbol : null;
    }

    private static bool InheritsFromSmartModel(INamedTypeSymbol typeSymbol)
    {
        INamedTypeSymbol? baseType = typeSymbol.BaseType;
        while (baseType != null)
        {
            if (baseType.Name == "SmartModel" && baseType.ContainingNamespace.ToDisplayString().Contains("Rymote.Radiant.Smart"))
                return true;

            baseType = baseType.BaseType;
        }

        return false;
    }

    private static string GenerateHelperMethods(INamedTypeSymbol classSymbol)
    {
        StringBuilder sourceBuilder = new StringBuilder();
        string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        string className = classSymbol.Name;

        sourceBuilder.AppendLine("// <auto-generated/>");
        sourceBuilder.AppendLine("#nullable enable");
        sourceBuilder.AppendLine($"namespace {namespaceName};");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine($"public static class {className}SmartQueryExtensions");
        sourceBuilder.AppendLine("{");

        ImmutableArray<IPropertySymbol> properties = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(property => property.DeclaredAccessibility == Accessibility.Public)
            .Where(property => !IsRelationshipProperty(property))
            .ToImmutableArray();

        foreach (IPropertySymbol property in properties)
            GeneratePropertyHelperMethods(sourceBuilder, className, property);

        sourceBuilder.AppendLine("}");
        return sourceBuilder.ToString();
    }

    private static void GeneratePropertyHelperMethods(StringBuilder sourceBuilder, string className, IPropertySymbol property)
    {
        string propertyName = property.Name;
        string columnName = GetColumnName(property);
        ITypeSymbol propertyType = property.Type;

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        {GetFullTypeName(propertyType)} value)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \"=\", value);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}Not(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        {GetFullTypeName(propertyType)} value)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \"!=\", value);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        if (IsNumericType(propertyType))
            GenerateNumericHelperMethods(sourceBuilder, className, propertyName, columnName, propertyType);
        else if (IsDateTimeType(propertyType))
            GenerateDateTimeHelperMethods(sourceBuilder, className, propertyName, columnName, propertyType);
        else if (propertyType.SpecialType == SpecialType.System_String)
            GenerateStringHelperMethods(sourceBuilder, className, propertyName, columnName);
        else if (IsBooleanType(propertyType))
            GenerateBooleanHelperMethods(sourceBuilder, className, propertyName, columnName);

        if (IsNullableType(propertyType))
            GenerateNullableHelperMethods(sourceBuilder, className, propertyName, columnName);
    }

    private static void GenerateNumericHelperMethods(StringBuilder sourceBuilder, string className, string propertyName, string columnName, ITypeSymbol propertyType)
    {
        string typeName = GetFullTypeName(propertyType);

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}GreaterThan(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        {typeName} value)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \">\", value);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}GreaterThanOrEqual(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        {typeName} value)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \">=\", value);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}LessThan(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        {typeName} value)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \"<\", value);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}LessThanOrEqual(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        {typeName} value)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \"<=\", value);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}Between(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        {typeName} minValue,");
        sourceBuilder.AppendLine($"        {typeName} maxValue)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \">=\", minValue).Where(\"{columnName}\", \"<=\", maxValue);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();
    }

    private static void GenerateDateTimeHelperMethods(StringBuilder sourceBuilder, string className, string propertyName, string columnName, ITypeSymbol propertyType)
    {
        string typeName = GetFullTypeName(propertyType);

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}After(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        {typeName} value)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \">\", value);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}Before(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        {typeName} value)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \"<\", value);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}Between(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        {typeName} startDate,");
        sourceBuilder.AppendLine($"        {typeName} endDate)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \">=\", startDate).Where(\"{columnName}\", \"<=\", endDate);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}Today(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        global::System.DateTime today = global::System.DateTime.UtcNow.Date;");
        sourceBuilder.AppendLine($"        global::System.DateTime tomorrow = today.AddDays(1);");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \">=\", today).Where(\"{columnName}\", \"<\", tomorrow);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}ThisWeek(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        global::System.DateTime today = global::System.DateTime.UtcNow.Date;");
        sourceBuilder.AppendLine($"        int daysUntilMonday = ((int)today.DayOfWeek - (int)global::System.DayOfWeek.Monday + 7) % 7;");
        sourceBuilder.AppendLine($"        global::System.DateTime weekStart = today.AddDays(-daysUntilMonday);");
        sourceBuilder.AppendLine($"        global::System.DateTime weekEnd = weekStart.AddDays(7);");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \">=\", weekStart).Where(\"{columnName}\", \"<\", weekEnd);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}ThisMonth(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        global::System.DateTime today = global::System.DateTime.UtcNow;");
        sourceBuilder.AppendLine($"        global::System.DateTime monthStart = new global::System.DateTime(today.Year, today.Month, 1);");
        sourceBuilder.AppendLine($"        global::System.DateTime monthEnd = monthStart.AddMonths(1);");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \">=\", monthStart).Where(\"{columnName}\", \"<\", monthEnd);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();
    }

    private static void GenerateStringHelperMethods(StringBuilder sourceBuilder, string className, string propertyName, string columnName)
    {
        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}Like(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        string pattern)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \"LIKE\", pattern);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}Contains(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        string value)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \"LIKE\", $\"%{{value}}%\");");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}StartsWith(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        string value)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \"LIKE\", $\"{{value}}%\");");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}EndsWith(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query,");
        sourceBuilder.AppendLine($"        string value)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \"LIKE\", $\"%{{value}}\");");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();
    }

    private static void GenerateBooleanHelperMethods(StringBuilder sourceBuilder, string className, string propertyName, string columnName)
    {
        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}IsTrue(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \"=\", true);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}IsFalse(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.Where(\"{columnName}\", \"=\", false);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();
    }

    private static void GenerateNullableHelperMethods(StringBuilder sourceBuilder, string className, string propertyName, string columnName)
    {
        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}IsNull(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.WhereNull(\"{columnName}\");");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"    public static global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> Where{propertyName}IsNotNull(");
        sourceBuilder.AppendLine($"        this global::Rymote.Radiant.Smart.Query.ISmartQuery<{className}> query)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        return query.WhereNotNull(\"{columnName}\");");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();
    }

    private static string GetColumnName(IPropertySymbol property)
    {
        AttributeData? columnAttribute = property.GetAttributes()
            .FirstOrDefault(attribute => attribute.AttributeClass?.Name == "ColumnAttribute");

        if (columnAttribute != null && columnAttribute.ConstructorArguments.Length > 0)
        {
            object? value = columnAttribute.ConstructorArguments[0].Value;
            if (value is string columnName)
                return columnName;
        }

        return ConvertToSnakeCase(property.Name);
    }

    private static string ConvertToSnakeCase(string propertyName)
    {
        return string.Concat(propertyName.Select((character, index) =>
                index > 0 && char.IsUpper(character) ? "_" + character : character.ToString()))
            .ToLower();
    }

    private static bool IsRelationshipProperty(IPropertySymbol property)
    {
        return property.GetAttributes().Any(attribute =>
            attribute.AttributeClass?.Name == "HasManyAttribute" ||
            attribute.AttributeClass?.Name == "HasOneAttribute" ||
            attribute.AttributeClass?.Name == "BelongsToAttribute");
    }

    private static bool IsNumericType(ITypeSymbol type)
    {
        ITypeSymbol underlyingType = GetUnderlyingType(type);
        return underlyingType.SpecialType == SpecialType.System_Int16 ||
               underlyingType.SpecialType == SpecialType.System_Int32 ||
               underlyingType.SpecialType == SpecialType.System_Int64 ||
               underlyingType.SpecialType == SpecialType.System_Decimal ||
               underlyingType.SpecialType == SpecialType.System_Single ||
               underlyingType.SpecialType == SpecialType.System_Double;
    }

    private static bool IsDateTimeType(ITypeSymbol type)
    {
        ITypeSymbol underlyingType = GetUnderlyingType(type);
        return underlyingType.Name == "DateTime" || underlyingType.Name == "DateTimeOffset" ||
               underlyingType.Name == "DateOnly" || underlyingType.Name == "TimeOnly";
    }

    private static bool IsBooleanType(ITypeSymbol type)
    {
        ITypeSymbol underlyingType = GetUnderlyingType(type);
        return underlyingType.SpecialType == SpecialType.System_Boolean;
    }

    private static bool IsNullableType(ITypeSymbol type)
    {
        return type.NullableAnnotation == NullableAnnotation.Annotated ||
               (type is INamedTypeSymbol namedType && namedType.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T);
    }

    private static ITypeSymbol GetUnderlyingType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType && namedType.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
            return namedType.TypeArguments[0];

        return type;
    }

    private static string GetFullTypeName(ITypeSymbol type)
    {
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static string GenerateResultMapper(INamedTypeSymbol classSymbol)
    {
        string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        string className = classSymbol.Name;
        string fullyQualifiedClassName = $"global::{namespaceName}.{className}";

        ImmutableArray<IPropertySymbol> properties = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(property => property.DeclaredAccessibility == Accessibility.Public)
            .Where(property => !IsRelationshipProperty(property))
            .Where(property => property.SetMethod is not null)
            .ToImmutableArray();

        StringBuilder sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("// <auto-generated/>");
        sourceBuilder.AppendLine("#nullable enable");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine($"namespace Rymote.Radiant.GeneratedMappers;");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("/// <summary>");
        sourceBuilder.AppendLine($"/// Source-generated DbDataReader -> {fullyQualifiedClassName} mapper. Registered with");
        sourceBuilder.AppendLine($"/// <c>Rymote.Radiant.Smart.Mapping.SourceGeneratedMapperRegistry</c> at module load time via");
        sourceBuilder.AppendLine($"/// the <c>[ModuleInitializer]</c> attribute below; from then on, every query that returns");
        sourceBuilder.AppendLine($"/// <c>{className}</c> goes through this mapper instead of Dapper's reflection-based mapping.");
        sourceBuilder.AppendLine("/// </summary>");
        sourceBuilder.AppendLine($"internal static class {className}RadiantResultMapper");
        sourceBuilder.AppendLine("{");
        sourceBuilder.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sourceBuilder.AppendLine("    internal static void RegisterWithRadiant()");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        global::Rymote.Radiant.Smart.Mapping.SourceGeneratedMapperRegistry.Register<{fullyQualifiedClassName}>(MapFromReader);");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine($"    public static {fullyQualifiedClassName} MapFromReader(global::System.Data.Common.DbDataReader reader)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine($"        {fullyQualifiedClassName} result = new {fullyQualifiedClassName}();");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("        for (int columnIndex = 0; columnIndex < reader.FieldCount; columnIndex++)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            string columnName = reader.GetName(columnIndex);");
        sourceBuilder.AppendLine("            bool columnIsNull = reader.IsDBNull(columnIndex);");
        sourceBuilder.AppendLine("            switch (columnName)");
        sourceBuilder.AppendLine("            {");

        foreach (IPropertySymbol property in properties)
        {
            string propertyName = property.Name;
            string columnName = GetColumnName(property);
            string columnNameAlias = propertyName;

            sourceBuilder.AppendLine($"                case \"{columnName}\":");
            if (columnName != columnNameAlias)
                sourceBuilder.AppendLine($"                case \"{columnNameAlias}\":");

            string readerExpression = BuildReaderExpressionForProperty(property);
            string defaultExpression = BuildDefaultExpressionForProperty(property);

            if (IsNullableType(property.Type) || !property.Type.IsValueType)
            {
                sourceBuilder.AppendLine($"                    result.{propertyName} = columnIsNull ? {defaultExpression} : {readerExpression};");
            }
            else
            {
                sourceBuilder.AppendLine($"                    if (!columnIsNull) result.{propertyName} = {readerExpression};");
            }

            sourceBuilder.AppendLine("                    break;");
        }

        sourceBuilder.AppendLine("            }");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("        return result;");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine("}");

        return sourceBuilder.ToString();
    }

    private static string BuildReaderExpressionForProperty(IPropertySymbol property)
    {
        ITypeSymbol underlyingType = GetUnderlyingType(property.Type);
        string fullyQualifiedType = GetFullTypeName(underlyingType);

        // jsonb / json columns are emitted as strings by Postgres and must be deserialised into
        // the CLR type via System.Text.Json. The [Column(..., databaseType: "jsonb")] hint on the
        // property carries this information, so the generated mapper reads the column as a string
        // and routes it through JsonSerializer.Deserialize. Without this branch the row mapper
        // would call reader.GetFieldValue<List<T>> which Npgsql cannot satisfy for jsonb columns.
        string? databaseType = GetColumnDatabaseType(property);
        if (databaseType is "jsonb" or "json")
        {
            return $"global::System.Text.Json.JsonSerializer.Deserialize<{fullyQualifiedType}>(reader.GetString(columnIndex))!";
        }

        return underlyingType.SpecialType switch
        {
            SpecialType.System_Boolean => "reader.GetBoolean(columnIndex)",
            SpecialType.System_Byte    => "reader.GetByte(columnIndex)",
            SpecialType.System_Char    => "reader.GetChar(columnIndex)",
            SpecialType.System_Int16   => "reader.GetInt16(columnIndex)",
            SpecialType.System_Int32   => "reader.GetInt32(columnIndex)",
            SpecialType.System_Int64   => "reader.GetInt64(columnIndex)",
            SpecialType.System_Single  => "reader.GetFloat(columnIndex)",
            SpecialType.System_Double  => "reader.GetDouble(columnIndex)",
            SpecialType.System_Decimal => "reader.GetDecimal(columnIndex)",
            SpecialType.System_String  => "reader.GetString(columnIndex)",
            SpecialType.System_DateTime => "reader.GetDateTime(columnIndex)",
            _ when underlyingType.Name == "Guid" => "reader.GetGuid(columnIndex)",
            // Non-primitive types may have a registered ValueConverter; route through the runtime
            // registry. When no converter is registered for this CLR type the helper falls back to
            // reader.GetFieldValue<T>(), preserving the original behaviour for types the provider
            // already understands.
            _ => $"global::Rymote.Radiant.Smart.Mapping.ValueConverterRuntimeRegistry.Read<{fullyQualifiedType}>(reader, columnIndex)"
        };
    }

    private static string? GetColumnDatabaseType(IPropertySymbol property)
    {
        AttributeData? columnAttribute = property.GetAttributes()
            .FirstOrDefault(attribute => attribute.AttributeClass?.Name == "ColumnAttribute");
        if (columnAttribute is null) return null;

        foreach (KeyValuePair<string, TypedConstant> namedArgument in columnAttribute.NamedArguments)
        {
            if (namedArgument.Key == "databaseType" && namedArgument.Value.Value is string namedValue)
                return namedValue;
        }

        if (columnAttribute.ConstructorArguments.Length >= 4 &&
            columnAttribute.ConstructorArguments[3].Value is string positionalValue)
        {
            return positionalValue;
        }

        return null;
    }

    private static string BuildDefaultExpressionForProperty(IPropertySymbol property)
    {
        ITypeSymbol underlyingType = GetUnderlyingType(property.Type);
        if (underlyingType.SpecialType == SpecialType.System_String)
            return IsNullableType(property.Type) ? "null" : "string.Empty";

        return $"default({GetFullTypeName(property.Type)})";
    }
}
