using System.Data;
using System.Reflection;
using Dapper;
using Rymote.Radiant.Core;
using Rymote.Radiant.Core.Attributes;
using Rymote.Radiant.Query;

namespace Rymote.Radiant.Models;

public abstract class Model<TKey> : IDbModel<TKey>
{
    public TKey Id { get; set; } = default!;

    protected static IDbConnection? dbConnection;
    protected static string? defaultSchema;

    public static void Configure(IDbConnection connection, string schema = "public")
    {
        dbConnection = connection;
        defaultSchema = schema;
    }

    protected static string GetTableName<T>()
    {
        Type type = typeof(T);
        TableAttribute? tableAttr = type.GetCustomAttribute<TableAttribute>();
        return tableAttr?.Name ?? type.Name.ToLowerInvariant();
    }

    protected static string GetSchema<T>()
    {
        Type type = typeof(T);
        TableAttribute? tableAttr = type.GetCustomAttribute<TableAttribute>();
        return tableAttr?.Schema ?? defaultSchema ?? "public";
    }

    public static QueryBuilder<T> Query<T>() where T : class
    {
        if (dbConnection == null)
            throw new InvalidOperationException("Database connection not configured. Call Configure() first.");
        
        return new QueryBuilder<T>(dbConnection, GetTableName<T>(), GetSchema<T>());
    }

    public static PaginatedQueryBuilder<T> QueryPaginated<T>() where T : class
    {
        if (dbConnection == null)
            throw new InvalidOperationException("Database connection not configured. Call Configure() first.");
        
        return new PaginatedQueryBuilder<T>(dbConnection, GetTableName<T>(), GetSchema<T>());
    }

    public static async Task<IEnumerable<T>> AllAsync<T>() where T : class
    {
        return await Query<T>().GetAsync();
    }

    public static async Task<T?> FindAsync<T>(object id) where T : class
    {
        return await Query<T>().Where("id", "=", id).FirstOrDefaultAsync();
    }

    public static async Task<T> FindOrFailAsync<T>(object id) where T : class
    {
        T? result = await FindAsync<T>(id);
        if (result == null)
            throw new InvalidOperationException($"Record with id {id} not found");
        return result;
    }

    public static async Task<T> CreateAsync<T>(T model) where T : class
    {
        if (dbConnection == null)
            throw new InvalidOperationException("Database connection not configured");

        Type type = typeof(T);
        string tableName = GetTableName<T>();
        string schema = GetSchema<T>();

        List<string> columns = new();
        List<string> values = new();
        DynamicParameters parameters = new();

        foreach (PropertyInfo property in type.GetProperties())
        {
            var pkAttr = property.GetCustomAttribute<PrimaryKeyAttribute>();
            if (pkAttr != null && pkAttr.AutoGenerated)
                continue;

            // Skip the base Id property if it's auto-generated
            if (property.Name == "Id" && property.DeclaringType == typeof(Model<TKey>))
                continue;

            ColumnAttribute? columnAttr = property.GetCustomAttribute<ColumnAttribute>();
            string columnName = columnAttr?.Name ?? property.Name.ToLowerInvariant();
            
            columns.Add($"\"{columnName}\"");
            values.Add($"@{property.Name}");
            parameters.Add(property.Name, property.GetValue(model));
        }

        string sql = $"""
            INSERT INTO "{schema}"."{tableName}" ({string.Join(", ", columns)})
            VALUES ({string.Join(", ", values)})
            RETURNING *
            """;

        return await dbConnection.QuerySingleAsync<T>(sql, parameters);
    }

    public static async Task<int> UpdateAsync<T>(object id, object updateValues) where T : class
    {
        return await Query<T>().Where("id", "=", id).UpdateAsync(updateValues);
    }

    public static async Task<int> DeleteAsync<T>(object id) where T : class
    {
        return await Query<T>().Where("id", "=", id).DeleteAsync();
    }

    public static async Task<bool> ExistsAsync<T>(object id) where T : class
    {
        return await Query<T>().Where("id", "=", id).ExistsAsync();
    }

    public virtual async Task<T> SaveAsync<T>() where T : class
    {
        if (dbConnection == null)
            throw new InvalidOperationException("Database connection not configured");

        if (Id != null && !Id.Equals(default(TKey)))
        {
            // Update existing record
            await UpdateAsync<T>(Id, this);
            return (T)(object)this;
        }
        else
        {
            // Create new record
            var created = await CreateAsync((T)(object)this);
            
            // Copy all properties from created back to this instance
            foreach (var prop in typeof(T).GetProperties())
            {
                if (prop.CanWrite && prop.CanRead)
                {
                    var value = prop.GetValue(created);
                    prop.SetValue(this, value);
                }
            }
            
            return (T)(object)this;
        }
    }

    public virtual async Task<int> DeleteAsync()
    {
        if (Id == null || Id.Equals(default(TKey)))
            throw new InvalidOperationException("Cannot delete record without ID");

        // Use the actual type of this instance
        var type = this.GetType();
        var method = typeof(Model<TKey>).GetMethod(nameof(DeleteAsync), BindingFlags.Public | BindingFlags.Static);
        var genericMethod = method!.MakeGenericMethod(type);
        var task = (Task<int>)genericMethod.Invoke(null, new object[] { Id })!;
        return await task;
    }
}
